// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_ydnERel0fVeRX330Z0VKBkWIuCyMDs',
    appId: '1:50710967065:web:4fd1d710e7cf8dd9274b88',
    messagingSenderId: '50710967065',
    projectId: 'chatapp-279e3',
    authDomain: 'chatapp-279e3.firebaseapp.com',
    storageBucket: 'chatapp-279e3.appspot.com',
    measurementId: 'G-KY8Z9W52PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-xFfPUhJesxG3niz4ji0l-7g6zsBSl4',
    appId: '1:50710967065:android:9fa99cd5921e6955274b88',
    messagingSenderId: '50710967065',
    projectId: 'chatapp-279e3',
    storageBucket: 'chatapp-279e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxUEonYiY-MdRY6kscPZnrifErZ1GOIf0',
    appId: '1:50710967065:ios:e2ce57178c5c4558274b88',
    messagingSenderId: '50710967065',
    projectId: 'chatapp-279e3',
    storageBucket: 'chatapp-279e3.appspot.com',
    androidClientId: '50710967065-jhfo4lqie48d719at9kj3l2fhugv7mta.apps.googleusercontent.com',
    iosClientId: '50710967065-qt6hdonp8pe4qngb82ca90sb3idjvfuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxUEonYiY-MdRY6kscPZnrifErZ1GOIf0',
    appId: '1:50710967065:ios:e2ce57178c5c4558274b88',
    messagingSenderId: '50710967065',
    projectId: 'chatapp-279e3',
    storageBucket: 'chatapp-279e3.appspot.com',
    androidClientId: '50710967065-jhfo4lqie48d719at9kj3l2fhugv7mta.apps.googleusercontent.com',
    iosClientId: '50710967065-qt6hdonp8pe4qngb82ca90sb3idjvfuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX_ydnERel0fVeRX330Z0VKBkWIuCyMDs',
    appId: '1:50710967065:web:824b9abb4512b571274b88',
    messagingSenderId: '50710967065',
    projectId: 'chatapp-279e3',
    authDomain: 'chatapp-279e3.firebaseapp.com',
    storageBucket: 'chatapp-279e3.appspot.com',
    measurementId: 'G-1VPZ9GP8X9',
  );

}